<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataBridge.Application\DataBridge.Application.csproj" />
    <ProjectReference Include="..\DataBridge.Infrastructure\DataBridge.Infrastructure.csproj" />
  </ItemGroup>
</Project>
